	var ToolbarSet = {
		Default		:	
			[
				['SourceView', 'Preview', 'Print', 'FullScreen', '', 'NewDoc', 'Save', 'Open'],
				['Cut', 'Copy', 'Paste', 'Delete', 'SelectAll', 'RemoveFormat'],
				['Undo', 'Redo'],
				['Bold', 'Italic', 'UnderLine', 'StrikeThrough', '', 'Subscript', 'Superscript'],
				['Find', 'Replace', '', 'UpperCase', 'LowerCase'],
				['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyFull'],
				['InsertOrderedList', 'InsertUnorderedList', 'Outdent', 'Indent'],
				['InsertImage', 'InsertFlash', 'InsertMedia', 'InsertEmoticon', '', 'InsertBox', 'ModifyBox', '', 'InsertHorizontalRule', 'InsertChars'],
				['InsertLayer', 'InsertGroupBox', 'ShowBorders' , '', 'Absolute', 'Forward', 'Backward'],
				['InsertTable', 'ModifyTable', 'ModifyCell', 'DeleteTable', '', 'MergeCellCol', 'MergeCellRow', '', 'SplitCellCol', 'SplitCellRow', '', 'InsertRow', 'DeleteRow', '', 'InsertColumn', 'DeleteColumn'],
				['CreateLink', 'UnLink'],
				'newLine',
				['FontFormat', 'FontName', 'FontSize', 'EnterMode'],
				['ForeColor', 'BackColor'],
				['InsertLineBreak', '', 'AutoResize']
			],
		Simple		 :
			[
				['SourceView', 'Preview', '', 'NewDoc'],
				['FontName', 'FontSize'],
				['ForeColor', 'BackColor'],
				['Bold', 'Italic', 'UnderLine'],
				['InsertImage']
			]
	};

	var ToolBarDisplay = {
		/* menu name		:	[position, enable button display, button disable] */
		SourceView		:	[0, false, false],
		Preview			:	[1, false, false],
		FullScreen		:	[2, true, false],
		NewDoc			:	[3, false, false],
		Save			:	[4, false, false],
		Open	 		:	[5, false, false],
		Print	 		:	[6, false, false],
		Cut			:	[7, true, true],
		Copy			:	[8, true, true],
		Paste			:	[9, true, true],
		Delete			:	[10, true, true],
		SelectAll		:	[11, false, true],
		RemoveFormat		:	[12, false, true],
		Undo			:	[13, true, true],
		Redo			:	[14, true, true],
		Bold			:	[15, true, true],
		Italic			:	[16, true, true],
		UnderLine		:	[17, true, true],
		StrikeThrough		:	[18, true, true],
		Find			:	[19, true, true],
		Replace			:	[20, true, true],
		UpperCase		:	[21, true, true],
		LowerCase		:	[22, true, true],
		Subscript		:	[23, true, true],
		Superscript		:	[24, true, true],
		JustifyNone		:	[25, true, true],
		JustifyLeft		:	[26, true, true],
		JustifyCenter		:	[27, true, true],
		JustifyRight		:	[28, true, true],
		JustifyFull		:	[29, true, true],
		InsertOrderedList	:	[30, true, true],
		InsertUnorderedList	:	[31, true, true],
		Outdent			:	[32, true, true],
		Indent			:	[33, true, true],
		InsertLineBreak		:	[34, false, true],
		InsertPageBreak		:	[35, false, true],
		InsertHorizontalRule	:	[36, false, true],
		InsertDate		:	[37, false, true],
		InsertTime		:	[38, false, true],
		InsertEmoticon		:	[39, false, true],
		InsertImage		:	[40, false, true],
		InsertFlash		:	[41, false, true],
		InsertMedia		:	[42, false, true],
		InsertTable		:	[43, false, true],
		ModifyTable		:	[44, true, true],
		DeleteTable		:	[45, true, true],
		MergeCellCol		:	[46, true, true],
		MergeCellRow		:	[47, true, true],
		SplitCellCol		:	[48, true, true],
		SplitCellRow		:	[49, true, true],
		ModifyCell		:	[50, true, true],
		InsertRow		:	[51, true, true],
		DeleteRow		:	[52, true, true],
		InsertColumn		:	[53, true, true],
		DeleteColumn		:	[54, true, true],
		InsertChars		:	[55, false, true],
		InsertLayer		:	[56, false, true],
		InsertGroupBox		:	[57, false, true],
		InsertBox		:	[58, false, true],
		ModifyBox		:	[59, true, true],
		ShowBorders		:	[60, true, true],
		Absolute		:	[61, true, true],
		Forward			:	[62, true, true],
		Backward		:	[63, true, true],
		CreateLink		:	[64, false, true],
		UnLink			:	[65, true, true],
		AutoResize		:	[66, false, true],
		Help			:	[68, false, true],
		ForeColor		:	[69, true, true],
		BackColor		:	[70, true, true],
		BackgroundColor		:	[71, true, true],
		ArrowForeColor		:	[null, false, true],
		ArrowBackColor		:	[null, false, true],
		FontName		:	[null, true, true],
		FontSize		:	[null, true, true],
		FontFormat		:	[null, true, true],
		EnterMode		:	[null, true, true]
	};

	var ContextMenuIcon = {
		Cut			:	0,
		Copy			:	1,
		Paste			:	2,
		Delete			:	3,
		SelectAll		:	4,
		InsertImage		:	5,
		CreateLink		:	6,
		UnLink			:	7,
		MergeCellCol		:	8,
		MergeCellRow		:	9,
		SplitCellCol		:	10,
		SplitCellRow		:	11,
		ModifyCell		:	12,
		InsertRow		:	13,
		DeleteRow		:	14,
		InsertColumn		:	15,
		DeleteColumn		:	16,
		DeleteTable		:	17,
		ModifyTable		:	18
	}
